[tool.poetry]
name = "VacasaConnect"
version = "4.13.1"
description = ""
authors = []
packages = [{ include = "vacasa" }]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
