[tool.poetry]
name = "VacasaConnect"
version = "4.13.1"
description = ""
authors = []
packages = [{ include = "vacasa/connect" }]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
